GET http://localhost:9876/movies

### consulta de Pelis por ID

GET http://localhost:9876/movies/f3d28614-a66b-11ef-bb4c-daa54ca21784

### Consulta por genero de Peli

GET http://localhost:9876/movies?genre=DRAMA

### crear una nueva pelicula
POST http://localhost:9876/movies
Content-Type: application/json

{
  "title": "Titanic",
  "year": 1997,
  "director": "James Cameron",
  "duration": 195,
  "poster": "https://i.pinimg.com/originals/42/42/65/4242658e6f1b0d6322a4a93e0383108b.png",
  "genre": ["Drama", "Romance"],
  "rate": 7.8
}

### Actualizar una Peli
PATCH http://localhost:9876/movies/673887b02ad549bdab44d19e
Content-Type: application/json

{
  "year": 2025
}

### Eliminar Peli
DELETE  http://localhost:9876/movies/673887b02ad549bdab44d19e
