GET http://localhost:9876/movies

### consulta de Pelis por ID

GET http://localhost:9876/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Consulta por genero de Peli

GET http://localhost:9876/movies?genre=drama

### crear una nueva pelicula
POST http://localhost:9876/movies
Content-Type: application/json

{
  "title": "Inception",
  "year": 2010,
  "director": "Christopher Nolan",
  "duration": 148,
  "poster": "https://m.media-amazon.com/images/I/91Rc8cAmnAL._AC_UF1000,1000_QL80_.jpg",
  "genre": ["Action", "Adventure", "Sci-Fi"],
  "rate": 8.8
}

### Actualizar una Peli
PATCH http://localhost:9876/movies/673887b02ad549bdab44d19e
Content-Type: application/json

{
  "year": 2025
}

### Eliminar Peli
DELETE  http://localhost:9876/movies/673887b02ad549bdab44d19e
